### ISSUE TITLE
OpenAPI file with version other than 3.1.0 is marked invalid by editor

### ISSUE THREAD

**Issue by kcchu** [Redocly/redocly-vs-code#3]
**What happened?**

A specification file with OpenAPI version set to 2.x or 3.0.x is marked as invalid.

**What should have happened instead?**

OpenAPI 2., 3.0 and 3.1 should be supported as described in the extension description. The validation rules should reflect the version specified in the file automatically. 

**Screenshots**

<img width="696" alt="image" src="https://user-images.githubusercontent.com/800071/144178315-3879f0a8-687c-4a49-beaf-f76c8b3ddac0.png">

**Additional context**

Extension version: Release 0.1.0 (2021-11-18)
VS Code version: Version: 1.63.0-insider

**Comment by skadinna** [comment]
Thanks for the report!

Looking at your screenshot, it seems that the warning message you're seeing ("String does not match...") is not coming from the Redocly extension. Something else called `yaml-schema` is causing this. 

If the warning was reported by our extension, it would say "Redocly OpenAPI" instead of "yaml-schema", like in this screenshot:
![Screenshot_20211202_184658](https://user-images.githubusercontent.com/33730345/144476202-3cb2541a-0a69-4aac-afbd-d2f7ecd09e37.png)

Are you using some other OpenAPI-related extensions? Perhaps you can try to disable them temporarily, then reload VS Code and see if you're still getting the same warning.

**Comment by kcchu** [comment]
You are right. The error was produced by the redhat.vscode-yaml plugin instead. Thanks

**Comment by jeremyfiel** [comment]
openapi: 2.0.0 is invalid too.  it should be `swagger: 2.0.0`

OR 

`openapi: 3.0.0`
`openapi: 3.0.1`
`openapi: 3.0.2`
`openapi: 3.0.3`
`openapi: 3.1.0`

An OpenAPI document compatible with OAS 3.*.* contains a required [openapi](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#oasVersion) field which designates the semantic version of the OAS that it uses. (OAS 2.0 documents contain a top-level version field named [swagger](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swaggerObject) and value "2.0".)

https://github.com/OAI/OpenAPI-Specification/tree/main/versions
